steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build',
         '-t', 'gcr.io/$PROJECT_ID/backend',
         '-t', 'gcr.io/$PROJECT_ID/backend:build-$BUILD_ID',
         '-t', 'gcr.io/$PROJECT_ID/backend:commit-$SHORT_SHA',
         '-t', 'gcr.io/$PROJECT_ID/backend:branch-$BRANCH_NAME',
         '-t', 'gcr.io/$PROJECT_ID/backend:unstable',
         '.']
# TODO: run tests, then tag build as stable
#- name: 'gcr.io/cloud-builders/docker'
#  args: ['tag', 'gcr.io/$PROJECT_ID/backend', 'gcr.io/$PROJECT_ID/backend:stable']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/backend']
tags: ['backend']
images: ['gcr.io/$PROJECT_ID/backend']